### ISSUE TITLE
NMLDB customization

### ISSUE THREAD

**Issue by carlosharlens** [nutiteq/hellomap3d-android#10]
Hi Guys,

We would like to solve out how to achieve buildings height instead of getting a general mapboounds?.

I am wordering the sense of a group of buildings with no interaction at all.

Splitting them into nml ones we do guess is worthless rather.

**Comment by mtehver** [comment]
Hi Carlos,

why not store metainfo (like height, etc) in separate database?

**Comment by carlosharlens** [comment]
Am too lazy Mark. to code such. How about you provinding this database filed next release?.

Anyway, it is an add-on which pull your library up. think about it please.

Best regards,

**Comment by jaakla** [comment]
Thanks for the suggestion, maybe in the future; unless you find funding for the feature :). I'm closing the issue here as it is not demo app, but actual SDK feature request.
