### ISSUE TITLE
Use nutibright-v3.zip in AdvancedMap Sample

### ISSUE THREAD

**Issue by jaakla** [nutiteq/hellomap3d-android#20]
Advancedmap uses still older nutibright-v2a.zip , it would be nicer to use newer -v3 one, which is also included in SDK. Note that -v3 includes 3 styles - default, nutiteq_gray and nutiteq_dark, so the style selector should use specific method to pick one of these.

**Comment by Nikituh** [comment]
AdvancedMap no longer any nutibright.zip, it's bundled with the sdk

**Comment by jaakla** [comment]
Maybe we could keep one style file, otherwise there is no any sample to use custom style packages?

**Comment by Nikituh** [comment]
BaseMaps sample still uses custom mapzen style assets

**Comment by jaakla** [comment]
Ok then :)
