### ISSUE TITLE
how can I get the width and height of the billboard

### ISSUE THREAD

**Issue by kry4ever** [nutiteq/hellomap3d-android#21]
I use myEventListener in the sample，but in the callback 

@Override
public void onVectorElementClicked（）

I got the VectorElement and i use vectorElement.getBounds to get MapBounds
but why the MapBounds.getMax is the same with Mapbounds.getMin ？
Is not that should be a rectangle？

**Comment by jaakla** [comment]
What is your element? If it is Marker or Point, then min and max should be the same.
