### ISSUE TITLE
NUTITEQ map Style

### ISSUE THREAD

**Issue by carlosharlens** [nutiteq/hellomap3d-android#22]
Hi guys,

I've a map exported from Tilemill as mbtiles. So, can i lack of map nutiteq map style? i guess i do since map runs like a charm without any style dependencies.

**Comment by jaakla** [comment]
Yes. Tilemill generates raster mbtiles which already has styling applied.

**Comment by carlosharlens** [comment]
Thanks Jaak!

Very helpfull my friend.
