### ISSUE TITLE
PersistentCacheTileDataSource not deleted(cleared) cache data

### ISSUE THREAD

**Issue by oooits72** [nutiteq/hellomap3d-android#5]
I am use cache tile data source, and want clear cache in preference app, but cache not cleared
this example code:
 "TileDataSource online = new HTTPTileDataSource(0, 24, Constants.online_tiles);
                    PersistentCacheTileDataSource cachedDataSource =
                            new PersistentCacheTileDataSource(online, contextWrapper.getFilesDir().getAbsolutePath() + "/" + cacheDb);
                    cachedDataSource.clear();"
after that call :
"cachedDataSource.getCapacity()" and capacity not changed
try call delete method and nothing changed

**Comment by mtehver** [comment]
PersistentCacheTileDataSource.clear() does not change the capacity (which is the maximum size of the cache), so this is not a bug. Note that clearing the cache should normally not have any visual impact - the next time a tile is queried from the PersistentCacheTileDataSource, the request will be simply forwarded to HTTPTileDataSource in your case.

Perhaps you are monitoring the size of the cache file? Clearing the cache does not change the file size in 3.0.0 release, though the cache is correctly flushed. We will change this in 3.0.1 - the cache file size will be reduced to couple to kilobytes.

**Comment by oooits72** [comment]
thankyou
