### ISSUE TITLE
Problem with DrawerLayout and Mapview

### ISSUE THREAD

**Issue by carlosharlens** [nutiteq/hellomap3d-android#6]
Hi,

I wonder why once layout containing mapview component opens, and tap home button toolbar, menu drawerlayout opens but it gets behind mapview, not in first Z order.

I´ve tryied all possible ways, even demo uploaded by nutiteq in this order non results at all.

Please help!

**Comment by jaakla** [comment]
Please make sure you use latest version update. I think I saw such issue in one app, with some devices, but it was fixed.

Jaak

**Comment by mtehver** [comment]
Hi,

this seems to be a bug in some Android versions - GLSurfaceView (the base class of MapView) and DrawerLayout do not mix well. This stackoverflow thread describes a workaround (we have used it ourselves and it really works): 

http://stackoverflow.com/questions/23691012/drawerlayout-listview-not-drawn-with-glsurfaceview-as-content

**Comment by carlosharlens** [comment]
Thanks! i´ll try out ASAP. let you know afterwards.

Maybe you´ve seen mapview gets white sometimes when panning... is it GSSurfaceview realted also? guess why.

**Comment by carlosharlens** [comment]
wow!! It works like a charm mtehver!!!
Didnt realize at first place but now am totally convinced it is solution.

Dont understand why both components dont get well mixed... However google maps for android works quite good having "same" components also.

Well, thanks you very much for your tip and trick.

**Comment by carlosharlens** [comment]
Jaak,

As you can check, this issue is been solve, so you could close this thread. thank you both guys.
