### ISSUE TITLE
New 3d Models adition

### ISSUE THREAD

**Issue by carlosharlens** [nutiteq/hellomap3d-android#7]
Hi Nutiteq Group,

1) I´d like to ask if it is any chance to send new 3d models to you in order to be converted into nmldb file?

2) What is the minimal requeriments for meemorychache size and texturecache settings on code in order to get a soft map panning after loading  a model database 75mb heavy?

3) I´d like to ask for Pro license quotation.

**Comment by jaakla** [comment]
Closing old question - the right channel would be licensing@nutiteq.com for this kind of requests, and Carlos has already got the answer.
